name: build 
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  build-wasm: 
    name: build-wasm
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nxxm builds project 
        run: |
          tipi . --dont-upgrade --verbose --test all -t wasm-cxx17
  build-clang-linux: 
    name: build-clang-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nxxm builds project 
        run: |
          tipi . --dont-upgrade --verbose --test all -t linux-cxx17
